# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('info', 'normal'), ('success', 'low'), ('danger', 'high')], default='normal', max_length=50),
            preserve_default=False,
        ),
    ]
